USE BHARATH;

CREATE TABLE STUDENT(
   ID INT PRIMARY KEY,
   NAME VARCHAR(30),
   GPA DECIMAL(3,2)
   );
   
   DESCRIBE STUDENT;
   DROP TABLE STUDENT;
   
   ALTER TABLE STUDENT ADD DEPARTMENT VARCHAR(10);
   ALTER TABLE STUDENT DROP DEPARTMENT;
   
   INSERT INTO STUDENT VALUES( 1,"AARTHI",7.6);
   INSERT INTO STUDENT VALUES( 2,"ANITHA",8.6);
   INSERT INTO STUDENT VALUES( 3,"ANITHA",9.6);
   
    INSERT INTO STUDENT VALUES( 4,"ANITHA",6.6),
    (5,"AVA",7.8),(6,"ADAMS",8.0);
    
    
    INSERT INTO STUDENT(ID,NAME) VALUES(7,"BALU");
   
   
   
   SELECT ID,NAME FROM STUDENT;